-- ── Step 1: Drop old constraint ──────────────────────────────────────────────
ALTER TABLE products DROP CONSTRAINT IF EXISTS products_type_check;

-- ── Step 2: Clear old products first (sales.product_id → SET NULL) ───────────
DELETE FROM products;
ALTER SEQUENCE products_id_seq RESTART WITH 1;

-- ── Step 3: Add new constraint (table is empty now — no violations) ───────────
ALTER TABLE products ADD CONSTRAINT products_type_check
  CHECK (type IN (
    'dino', 'boss', 'basic_resource', 'advanced_resource',
    'consumable', 'dye', 'weapon', 'armor', 'saddle',
    'tek_structure', 'metal_structure', 'utility'
  ));

-- ── Step 4: Add quantity column ───────────────────────────────────────────────
ALTER TABLE products ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT NULL;

-- ── Step 4: Insert all ARK shop items ────────────────────────────────────────
INSERT INTO products (sku, name, price, type, quantity, active) VALUES

-- DINO
('dino-001', 'Rex',                  8, 'dino', NULL, true),
('dino-002', 'Giganotosaurus',       8, 'dino', NULL, true),
('dino-003', 'Spinosaurus',          8, 'dino', NULL, true),
('dino-004', 'Allosaurus',           8, 'dino', NULL, true),
('dino-005', 'Carnotaurus',          8, 'dino', NULL, true),
('dino-006', 'Yutyrannus',           8, 'dino', NULL, true),
('dino-007', 'Therizinosaurus',      8, 'dino', NULL, true),
('dino-008', 'Baryonyx',             8, 'dino', NULL, true),
('dino-009', 'Raptor',               8, 'dino', NULL, true),
('dino-010', 'Dilophosaurus',        8, 'dino', NULL, true),
('dino-011', 'Megalodon',            8, 'dino', NULL, true),
('dino-012', 'Mosasaurus',           8, 'dino', NULL, true),
('dino-013', 'Plesiosaur',           8, 'dino', NULL, true),
('dino-014', 'Sarcosuchus',          8, 'dino', NULL, true),
('dino-015', 'Kaprosuchus',          8, 'dino', NULL, true),
('dino-016', 'Dimetrodon',           8, 'dino', NULL, true),
('dino-017', 'Sabertooth',           8, 'dino', NULL, true),
('dino-018', 'Direwolf',             8, 'dino', NULL, true),
('dino-019', 'Thylacoleo',           8, 'dino', NULL, true),
('dino-020', 'Shadowmane',           8, 'dino', NULL, true),
('dino-021', 'Brontosaurus',         8, 'dino', NULL, true),
('dino-022', 'Diplodocus',           8, 'dino', NULL, true),
('dino-023', 'Triceratops',          8, 'dino', NULL, true),
('dino-024', 'Stegosaurus',          8, 'dino', NULL, true),
('dino-025', 'Ankylosaurus',         8, 'dino', NULL, true),
('dino-026', 'Parasaur',             8, 'dino', NULL, true),
('dino-027', 'Iguanodon',            8, 'dino', NULL, true),
('dino-028', 'Pachycephalosaurus',   8, 'dino', NULL, true),
('dino-029', 'Mammoth',              8, 'dino', NULL, true),
('dino-030', 'Woolly Rhino',         8, 'dino', NULL, true),
('dino-031', 'Doedicurus',           8, 'dino', NULL, true),
('dino-032', 'Gacha',                8, 'dino', NULL, true),
('dino-033', 'Morellatops',          8, 'dino', NULL, true),
('dino-034', 'Carbonemys',           8, 'dino', NULL, true),
('dino-035', 'Castoroides',          8, 'dino', NULL, true),
('dino-036', 'Phiomia',              8, 'dino', NULL, true),
('dino-037', 'Pachyrhinosaurus',     8, 'dino', NULL, true),
('dino-038', 'Kentrosaurus',         8, 'dino', NULL, true),
('dino-039', 'Chalicotherium',       8, 'dino', NULL, true),
('dino-040', 'Managarmr',            8, 'dino', NULL, true),
('dino-041', 'Pteranodon',           8, 'dino', NULL, true),
('dino-042', 'Quetzalcoatlus',       8, 'dino', NULL, true),
('dino-043', 'Argentavis',           8, 'dino', NULL, true),
('dino-044', 'Tapejara',             8, 'dino', NULL, true),
('dino-045', 'Griffin',              8, 'dino', NULL, true),
('dino-046', 'Wyvern (Fire)',        8, 'dino', NULL, true),
('dino-047', 'Wyvern (Lightning)',   8, 'dino', NULL, true),
('dino-048', 'Wyvern (Poison)',      8, 'dino', NULL, true),
('dino-049', 'Wyvern (Ice)',         8, 'dino', NULL, true),
('dino-050', 'Snow Owl',             8, 'dino', NULL, true),
('dino-051', 'Tropeognathus',        8, 'dino', NULL, true),
('dino-052', 'Pelagornis',           8, 'dino', NULL, true),
('dino-053', 'Dimorphodon',          8, 'dino', NULL, true),
('dino-054', 'Phoenix',              8, 'dino', NULL, true),
('dino-055', 'Desmodus',             8, 'dino', NULL, true),
('dino-056', 'Sinomacrops',          8, 'dino', NULL, true),
('dino-057', 'Basilosaurus',         8, 'dino', NULL, true),
('dino-058', 'Tusoteuthis',          8, 'dino', NULL, true),
('dino-059', 'Dunkleosteus',         8, 'dino', NULL, true),
('dino-060', 'Ichthyosaurus',        8, 'dino', NULL, true),
('dino-061', 'Manta',                8, 'dino', NULL, true),
('dino-062', 'Angler Fish',          8, 'dino', NULL, true),
('dino-063', 'Electrophorus',        8, 'dino', NULL, true),
('dino-064', 'Liopleurodon',         8, 'dino', NULL, true),
('dino-065', 'Astrocetus',           8, 'dino', NULL, true),
('dino-066', 'Rock Drake',           8, 'dino', NULL, true),
('dino-067', 'Magmasaur',            8, 'dino', NULL, true),
('dino-068', 'Bloodstalker',         8, 'dino', NULL, true),
('dino-069', 'Ferox',                8, 'dino', NULL, true),
('dino-070', 'Maewing',              8, 'dino', NULL, true),
('dino-071', 'Voidwyrm',             8, 'dino', NULL, true),
('dino-072', 'Noglin',               8, 'dino', NULL, true),
('dino-073', 'Stryder',              8, 'dino', NULL, true),
('dino-074', 'Fjordhawk',            8, 'dino', NULL, true),
('dino-075', 'Andrewsarchus',        8, 'dino', NULL, true),
('dino-076', 'Fenrir',               8, 'dino', NULL, true),

-- BOSS
('boss-001', 'Broodmother Lysrix',        15, 'boss', NULL, true),
('boss-002', 'Megapithecus',              15, 'boss', NULL, true),
('boss-003', 'Dragon',                    15, 'boss', NULL, true),
('boss-004', 'Overseer',                  15, 'boss', NULL, true),
('boss-005', 'Manticore',                 15, 'boss', NULL, true),
('boss-006', 'Rockwell',                  15, 'boss', NULL, true),
('boss-007', 'Rockwell Prime',            15, 'boss', NULL, true),
('boss-008', 'Desert Titan',              15, 'boss', NULL, true),
('boss-009', 'Ice Titan',                 15, 'boss', NULL, true),
('boss-010', 'Forest Titan',              15, 'boss', NULL, true),
('boss-011', 'King Titan',                15, 'boss', NULL, true),
('boss-012', 'Moeder',                    15, 'boss', NULL, true),
('boss-013', 'Corrupted Master Controller', 15, 'boss', NULL, true),
('boss-014', 'Crystal Wyvern Queen',      15, 'boss', NULL, true),
('boss-015', 'Dinopithecus King',         15, 'boss', NULL, true),
('boss-016', 'Tyranno Colossus',          40, 'boss', NULL, true),
('boss-017', 'Ouroboros',                 40, 'boss', NULL, true),
('boss-018', 'Vermis Rex',                40, 'boss', NULL, true),

-- BASIC RESOURCE
('bres-001', 'Metal Ingot',    15, 'basic_resource', 300, true),
('bres-002', 'Polymer',        15, 'basic_resource', 300, true),
('bres-003', 'Cementing Paste',15, 'basic_resource', 300, true),
('bres-004', 'Crystal',        15, 'basic_resource', 300, true),
('bres-005', 'Obsidian',       15, 'basic_resource', 300, true),
('bres-006', 'Silica Pearls',  15, 'basic_resource', 300, true),
('bres-007', 'Electronics',    15, 'basic_resource', 300, true),
('bres-008', 'Fiber',          15, 'basic_resource', 300, true),
('bres-009', 'Hide',           15, 'basic_resource', 300, true),
('bres-010', 'Chitin',         15, 'basic_resource', 300, true),
('bres-011', 'Keratin',        15, 'basic_resource', 300, true),
('bres-012', 'Thatch',         15, 'basic_resource', 300, true),
('bres-013', 'Wood',           15, 'basic_resource', 300, true),
('bres-014', 'Stone',          15, 'basic_resource', 300, true),
('bres-015', 'Flint',          15, 'basic_resource', 300, true),
('bres-016', 'Charcoal',       15, 'basic_resource', 300, true),
('bres-017', 'Gunpowder',      15, 'basic_resource', 300, true),
('bres-018', 'Sparkpowder',    15, 'basic_resource', 300, true),
('bres-019', 'Narcotics',      15, 'basic_resource', 300, true),
('bres-020', 'Stimulant',      15, 'basic_resource', 300, true),

-- ADVANCED RESOURCE
('ares-001', 'Element',             15, 'advanced_resource', 300, true),
('ares-002', 'Element Dust',        15, 'advanced_resource', 300, true),
('ares-003', 'Element Shard',       15, 'advanced_resource', 300, true),
('ares-004', 'Black Pearl',         15, 'advanced_resource', 300, true),
('ares-005', 'Organic Polymer',     15, 'advanced_resource', 300, true),
('ares-006', 'Absorbent Substrate', 15, 'advanced_resource', 300, true),
('ares-007', 'Ambergris',           15, 'advanced_resource', 300, true),
('ares-008', 'Congealed Gas Ball',  15, 'advanced_resource', 300, true),
('ares-009', 'Condensed Gas',       15, 'advanced_resource', 300, true),
('ares-010', 'Fungal Wood',         15, 'advanced_resource', 300, true),
('ares-011', 'Sap',                 15, 'advanced_resource', 300, true),
('ares-012', 'Rare Mushroom',       15, 'advanced_resource', 300, true),
('ares-013', 'Rare Flower',         15, 'advanced_resource', 300, true),
('ares-014', 'Biotoxin',            15, 'advanced_resource', 300, true),
('ares-015', 'Achatina Paste',      15, 'advanced_resource', 300, true),

-- CONSUMABLE
('cons-001', 'Kibble (Exceptional)',   15, 'consumable', 300, true),
('cons-002', 'Kibble (Extraordinary)', 15, 'consumable', 300, true),
('cons-003', 'Kibble (Superior)',      15, 'consumable', 300, true),
('cons-004', 'Kibble (Regular)',       15, 'consumable', 300, true),
('cons-005', 'Kibble (Simple)',        15, 'consumable', 300, true),
('cons-006', 'Kibble (Basic)',         15, 'consumable', 300, true),
('cons-007', 'Cryopod',               15, 'consumable', 300, true),
('cons-008', 'Mindwipe Tonic',        15, 'consumable', 300, true),
('cons-009', 'Sweet Vegetable Cake',  15, 'consumable', 300, true),
('cons-010', 'Medical Brew',          15, 'consumable', 300, true),
('cons-011', 'Energy Brew',           15, 'consumable', 300, true),
('cons-012', 'Lazarus Chowder',       15, 'consumable', 300, true),
('cons-013', 'Shadow Steak Saute',    15, 'consumable', 300, true),
('cons-014', 'Focal Chili',           15, 'consumable', 300, true),
('cons-015', 'Enduro Stew',           15, 'consumable', 300, true),
('cons-016', 'Fria Curry',            15, 'consumable', 300, true),
('cons-017', 'Calien Soup',           15, 'consumable', 300, true),
('cons-018', 'Bug Repellant',         15, 'consumable', 300, true),

-- DYE
('dye-001', 'Red Coloring',     15, 'dye', 300, true),
('dye-002', 'Blue Coloring',    15, 'dye', 300, true),
('dye-003', 'Green Coloring',   15, 'dye', 300, true),
('dye-004', 'Yellow Coloring',  15, 'dye', 300, true),
('dye-005', 'Purple Coloring',  15, 'dye', 300, true),
('dye-006', 'Orange Coloring',  15, 'dye', 300, true),
('dye-007', 'Black Coloring',   15, 'dye', 300, true),
('dye-008', 'White Coloring',   15, 'dye', 300, true),
('dye-009', 'Brown Coloring',   15, 'dye', 300, true),
('dye-010', 'Cyan Coloring',    15, 'dye', 300, true),
('dye-011', 'Magenta Coloring', 15, 'dye', 300, true),

-- WEAPON
('weap-001', 'Assault Rifle',          8,  'weapon', NULL, true),
('weap-002', 'Fabricated Sniper Rifle',9,  'weapon', NULL, true),
('weap-003', 'Pump-Action Shotgun',    8,  'weapon', NULL, true),
('weap-004', 'Longneck Rifle',         6,  'weapon', NULL, true),
('weap-005', 'Compound Bow',           7,  'weapon', NULL, true),
('weap-006', 'Sword',                  6,  'weapon', NULL, true),
('weap-007', 'Pike',                   6,  'weapon', NULL, true),
('weap-008', 'Rocket Launcher',        10, 'weapon', NULL, true),
('weap-009', 'C4 Charge',             7,  'weapon', NULL, true),
('weap-010', 'Tek Rifle',              10, 'weapon', NULL, true),
('weap-011', 'Tek Sword',              10, 'weapon', NULL, true),
('weap-012', 'Tek Bow',                9,  'weapon', NULL, true),
('weap-013', 'Harpoon Launcher',       6,  'weapon', NULL, true),
('weap-014', 'Flamethrower',           9,  'weapon', NULL, true),
('weap-015', 'Minigun',                10, 'weapon', NULL, true),

-- ARMOR
('armr-001', 'Flak Armor Set',            7,  'armor', NULL, true),
('armr-002', 'Riot Armor Set',            8,  'armor', NULL, true),
('armr-003', 'Ghillie Armor Set',         6,  'armor', NULL, true),
('armr-004', 'Tek Armor Set',             10, 'armor', NULL, true),
('armr-005', 'Hazard Suit Set',           7,  'armor', NULL, true),
('armr-006', 'Fur Armor Set',             6,  'armor', NULL, true),
('armr-007', 'Desert Cloth Set',          6,  'armor', NULL, true),
('armr-008', 'Chitin Armor Set',          6,  'armor', NULL, true),
('armr-009', 'SCUBA Set',                 7,  'armor', NULL, true),
('armr-010', 'Federation Tek Armor Set',  10, 'armor', NULL, true),

-- SADDLE
('sadl-001', 'Rex Saddle',            7,  'saddle', NULL, true),
('sadl-002', 'Giganotosaurus Saddle', 9,  'saddle', NULL, true),
('sadl-003', 'Quetzal Saddle',        8,  'saddle', NULL, true),
('sadl-004', 'Mosasaur Saddle',       8,  'saddle', NULL, true),
('sadl-005', 'Argentavis Saddle',     7,  'saddle', NULL, true),
('sadl-006', 'Yutyrannus Saddle',     8,  'saddle', NULL, true),
('sadl-007', 'Therizinosaurus Saddle',8,  'saddle', NULL, true),
('sadl-008', 'Tek Rex Saddle',        10, 'saddle', NULL, true),
('sadl-009', 'Tek Quetzal Saddle',    10, 'saddle', NULL, true),
('sadl-010', 'Rock Drake Saddle',     9,  'saddle', NULL, true),
('sadl-011', 'Astrocetus Tek Saddle', 10, 'saddle', NULL, true),
('sadl-012', 'Bronto Saddle',         7,  'saddle', NULL, true),
('sadl-013', 'Spinosaur Saddle',      7,  'saddle', NULL, true),
('sadl-014', 'Tapejara Tek Saddle',   10, 'saddle', NULL, true),
('sadl-015', 'Megalodon Tek Saddle',  9,  'saddle', NULL, true),

-- TEK STRUCTURE
('teks-001', 'Tek Foundation',        8, 'tek_structure', NULL, true),
('teks-002', 'Tek Wall',              8, 'tek_structure', NULL, true),
('teks-003', 'Tek Ceiling',           8, 'tek_structure', NULL, true),
('teks-004', 'Tek Door',              8, 'tek_structure', NULL, true),
('teks-005', 'Tek Gateway',           8, 'tek_structure', NULL, true),
('teks-006', 'Tek Gate',              8, 'tek_structure', NULL, true),
('teks-007', 'Tek Turret',            1, 'tek_structure', NULL, true),
('teks-008', 'Tek Generator',         8, 'tek_structure', NULL, true),
('teks-009', 'Tek Replicator',        8, 'tek_structure', NULL, true),
('teks-010', 'Tek Teleporter',        8, 'tek_structure', NULL, true),
('teks-011', 'Tek Transmitter',       8, 'tek_structure', NULL, true),
('teks-012', 'Tek Trough',            8, 'tek_structure', NULL, true),
('teks-013', 'Tek Shield Generator',  8, 'tek_structure', NULL, true),
('teks-014', 'Tek Forcefield',        8, 'tek_structure', NULL, true),
('teks-015', 'Tek Sleeping Pod',      8, 'tek_structure', NULL, true),
('teks-016', 'Tek Dedicated Storage', 8, 'tek_structure', NULL, true),

-- METAL STRUCTURE
('mets-001', 'Metal Foundation',      2, 'metal_structure', NULL, true),
('mets-002', 'Metal Wall',            2, 'metal_structure', NULL, true),
('mets-003', 'Metal Ceiling',         2, 'metal_structure', NULL, true),
('mets-004', 'Metal Door',            2, 'metal_structure', NULL, true),
('mets-005', 'Metal Gateway',         2, 'metal_structure', NULL, true),
('mets-006', 'Metal Behemoth Gate',   2, 'metal_structure', NULL, true),
('mets-007', 'Metal Spike Wall',      2, 'metal_structure', NULL, true),
('mets-008', 'Vault',                 2, 'metal_structure', NULL, true),
('mets-009', 'Industrial Forge',      2, 'metal_structure', NULL, true),
('mets-010', 'Industrial Cooker',     2, 'metal_structure', NULL, true),
('mets-011', 'Industrial Grinder',    2, 'metal_structure', NULL, true),
('mets-012', 'Chemistry Bench',       2, 'metal_structure', NULL, true),
('mets-013', 'Fabricator',            2, 'metal_structure', NULL, true),
('mets-014', 'Auto Turret',           1, 'metal_structure', NULL, true),
('mets-015', 'Heavy Auto Turret',     1, 'metal_structure', NULL, true),
('mets-016', 'Plant Species X Seed',  1, 'metal_structure', NULL, true),

-- UTILITY
('util-001', 'Air Conditioner',    2, 'utility', NULL, true),
('util-002', 'Refrigerator',       2, 'utility', NULL, true),
('util-003', 'Electrical Generator',2,'utility', NULL, true),
('util-004', 'Wind Turbine',       2, 'utility', NULL, true),
('util-005', 'Industrial Grill',   2, 'utility', NULL, true),
('util-006', 'Beer Barrel',        2, 'utility', NULL, true),
('util-007', 'Feeding Trough',     2, 'utility', NULL, true),
('util-008', 'Campfire',           2, 'utility', NULL, true),
('util-009', 'Standing Torch',     2, 'utility', NULL, true),
('util-010', 'Storage Box',        2, 'utility', NULL, true),
('util-011', 'Large Storage Box',  2, 'utility', NULL, true),
('util-012', 'Bookshelf',          2, 'utility', NULL, true),
('util-013', 'Elevator Platform',  2, 'utility', NULL, true),
('util-014', 'Zip-Line Anchor',    2, 'utility', NULL, true);
