-- ── Additional customers ─────────────────────────────────────────────────────
DELETE FROM customers WHERE email IN (
  'james.w@gmail.com','sofia.m@outlook.com','lucas.f@gmail.com','mia.k@gmail.com',
  'ethan.b@proton.me','chloe.d@gmail.com','noah.p@outlook.com','isa.r@gmail.com',
  'liam.o@gmail.com','emma.l@gmail.com','oliver.z@gmail.com','ava.m@outlook.com',
  'will.s@gmail.com','char.n@gmail.com','ben.h@gmail.com'
);

INSERT INTO customers (name, email, purchases, spent, discount, last_visit) VALUES
('James Whitfield',    'james.w@gmail.com',      61, 12400, 18, '2026-04-18'),
('Sofia Marchetti',    'sofia.m@outlook.com',     48,  9800, 15, '2026-04-17'),
('Lucas Fernandez',    'lucas.f@gmail.com',       37,  7200, 12, '2026-04-15'),
('Mia Kowalski',       'mia.k@gmail.com',         29,  5600, 10, '2026-04-14'),
('Ethan Blackwood',    'ethan.b@proton.me',       22,  4100,  8, '2026-04-10'),
('Chloe Dubois',       'chloe.d@gmail.com',       18,  3300,  7, '2026-04-08'),
('Noah Petersen',      'noah.p@outlook.com',      14,  2700,  5, '2026-04-05'),
('Isabella Romano',    'isa.r@gmail.com',         11,  2100,  5, '2026-03-28'),
('Liam Okafor',        'liam.o@gmail.com',         8,  1500,  3, '2026-03-22'),
('Emma Lindqvist',     'emma.l@gmail.com',         6,  1100,  3, '2026-03-18'),
('Oliver Zhang',       'oliver.z@gmail.com',       5,   820,  0, '2026-03-12'),
('Ava Morrison',       'ava.m@outlook.com',        4,   640,  0, '2026-03-05'),
('William Santos',     'will.s@gmail.com',         3,   440,  0, '2026-02-20'),
('Charlotte Nguyen',   'char.n@gmail.com',         2,   280,  0, '2026-02-10'),
('Benjamin Hoffmann',  'ben.h@gmail.com',          1,   120,  0, '2026-01-25');

-- ── Sales Jan–Apr 2026 ────────────────────────────────────────────────────────
INSERT INTO sales (staff_id, product_id, customer_id, qty, total, payment_status, created_at) VALUES

-- January 2026
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Rex' LIMIT 1),                (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),   1,  8, 'completed', '2026-01-03T10:14:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Metal Ingot' LIMIT 1),        (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1, 15, 'completed', '2026-01-04T13:22:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Giganotosaurus' LIMIT 1),     (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-01-05T09:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Dragon' LIMIT 1),             (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1, 15, 'completed', '2026-01-06T14:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Element' LIMIT 1),            (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    2, 30, 'completed', '2026-01-07T11:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Wyvern (Fire)' LIMIT 1),      (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-01-08T15:20:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Assault Rifle' LIMIT 1),      (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  8, 'completed', '2026-01-09T10:10:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Armor Set' LIMIT 1),      (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1, 10, 'completed', '2026-01-10T13:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Black Pearl' LIMIT 1),        (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1, 15, 'completed', '2026-01-12T09:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Rock Drake' LIMIT 1),         (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-01-13T14:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Broodmother Lysrix' LIMIT 1), (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-01-14T11:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Polymer' LIMIT 1),            (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1, 15, 'completed', '2026-01-15T16:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Rex Saddle' LIMIT 1),         (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  7, 'completed', '2026-01-16T10:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Snow Owl' LIMIT 1),           (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-01-18T13:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Kibble (Exceptional)' LIMIT 1),(SELECT id FROM customers WHERE email='isa.r@gmail.com' LIMIT 1),     2, 30, 'completed', '2026-01-19T09:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Giganotosaurus Saddle' LIMIT 1),(SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),  1,  9, 'completed', '2026-01-20T14:20:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Shadowmane' LIMIT 1),         (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-01-21T11:50:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Rifle' LIMIT 1),          (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1, 10, 'completed', '2026-01-22T15:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Cementing Paste' LIMIT 1),    (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-01-23T10:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Overseer' LIMIT 1),           (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1, 15, 'completed', '2026-01-25T13:00:00'),

-- February 2026
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Argentavis' LIMIT 1),         (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-02-01T10:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Element Dust' LIMIT 1),       (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      2, 30, 'completed', '2026-02-02T14:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Thylacoleo' LIMIT 1),         (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-02-03T09:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Flak Armor Set' LIMIT 1),     (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1,  7, 'completed', '2026-02-04T13:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Magmasaur' LIMIT 1),          (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  8, 'completed', '2026-02-05T11:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Silica Pearls' LIMIT 1),      (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-02-06T15:20:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='King Titan' LIMIT 1),         (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-02-07T10:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Foundation' LIMIT 1),     (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   3, 24, 'completed', '2026-02-08T14:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Griffin' LIMIT 1),            (SELECT id FROM customers WHERE email='isa.r@gmail.com' LIMIT 1),      1,  8, 'completed', '2026-02-10T09:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Electronics' LIMIT 1),        (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1, 15, 'completed', '2026-02-11T13:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Rocket Launcher' LIMIT 1),    (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1, 10, 'completed', '2026-02-12T11:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Wyvern (Lightning)' LIMIT 1), (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-02-13T15:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Organic Polymer' LIMIT 1),    (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-02-14T10:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Mindwipe Tonic' LIMIT 1),     (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  2, 30, 'completed', '2026-02-15T14:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Tek Turret' LIMIT 1),         (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   5,  5, 'completed', '2026-02-17T09:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Manticore' LIMIT 1),          (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-02-18T13:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Voidwyrm' LIMIT 1),           (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1,  8, 'completed', '2026-02-19T11:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Quetzal Saddle' LIMIT 1),     (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-02-20T15:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Crystal' LIMIT 1),            (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-02-21T10:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Replicator' LIMIT 1),     (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-02-22T14:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Compound Bow' LIMIT 1),       (SELECT id FROM customers WHERE email='isa.r@gmail.com' LIMIT 1),      1,  7, 'completed', '2026-02-24T09:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Desmodus' LIMIT 1),           (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  8, 'completed', '2026-02-25T13:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Element Shard' LIMIT 1),      (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1, 15, 'completed', '2026-02-26T11:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Rockwell Prime' LIMIT 1),     (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-02-27T15:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Auto Turret' LIMIT 1),        (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),     10, 10, 'completed', '2026-02-28T10:30:00'),

-- March 2026
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Spinosaurus' LIMIT 1),        (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-03-01T14:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Cryopod' LIMIT 1),            (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    3, 45, 'completed', '2026-03-02T09:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Sword' LIMIT 1),          (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 10, 'completed', '2026-03-03T13:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Mosasaurus' LIMIT 1),         (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  8, 'completed', '2026-03-04T11:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Absorbent Substrate' LIMIT 1),(SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-03-05T15:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Ankylosaurus' LIMIT 1),       (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1,  8, 'completed', '2026-03-06T10:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tyranno Colossus' LIMIT 1),   (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 40, 'completed', '2026-03-07T14:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Obsidian' LIMIT 1),           (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1, 15, 'completed', '2026-03-08T09:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Teleporter' LIMIT 1),     (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    2, 16, 'completed', '2026-03-09T13:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Phoenix' LIMIT 1),            (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-03-10T11:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Kibble (Superior)' LIMIT 1),  (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  2, 30, 'completed', '2026-03-11T15:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Wyvern (Ice)' LIMIT 1),       (SELECT id FROM customers WHERE email='isa.r@gmail.com' LIMIT 1),      1,  8, 'completed', '2026-03-12T10:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Metal Foundation' LIMIT 1),   (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    5, 10, 'completed', '2026-03-13T14:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Ouroboros' LIMIT 1),          (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 40, 'completed', '2026-03-14T09:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Sweet Vegetable Cake' LIMIT 1),(SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),  1, 15, 'completed', '2026-03-15T13:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Quetzalcoatlus' LIMIT 1),     (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1,  8, 'completed', '2026-03-16T11:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Generator' LIMIT 1),      (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-03-17T15:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Fabricated Sniper Rifle' LIMIT 1),(SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1), 1,  9, 'completed', '2026-03-18T10:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Ambergris' LIMIT 1),          (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1, 15, 'completed', '2026-03-19T14:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Mammoth' LIMIT 1),            (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  8, 'completed', '2026-03-20T09:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Riot Armor Set' LIMIT 1),     (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-03-21T13:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Ferox' LIMIT 1),              (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1,  8, 'completed', '2026-03-22T11:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Gunpowder' LIMIT 1),          (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      2, 30, 'completed', '2026-03-23T15:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Desert Titan' LIMIT 1),       (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-03-24T10:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Trough' LIMIT 1),         (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    2, 16, 'completed', '2026-03-25T14:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Bloodstalker' LIMIT 1),       (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-03-26T09:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Red Coloring' LIMIT 1),       (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1, 15, 'completed', '2026-03-27T13:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Vermis Rex' LIMIT 1),         (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 40, 'completed', '2026-03-28T11:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tapejara' LIMIT 1),           (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-03-29T15:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Minigun' LIMIT 1),            (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1, 10, 'completed', '2026-03-30T10:00:00'),

-- April 2026
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Direwolf' LIMIT 1),           (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1,  8, 'completed', '2026-04-01T14:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Congealed Gas Ball' LIMIT 1), (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-04-02T09:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Crystal Wyvern Queen' LIMIT 1),(SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),   1, 15, 'completed', '2026-04-03T13:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Argentavis Saddle' LIMIT 1),  (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  7, 'completed', '2026-04-04T11:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Element' LIMIT 1),            (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    3, 45, 'completed', '2026-04-05T15:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Pump-Action Shotgun' LIMIT 1),(SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),   1,  8, 'completed', '2026-04-06T10:30:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Managarmr' LIMIT 1),          (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   1,  8, 'completed', '2026-04-07T14:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Moeder' LIMIT 1),             (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-04-08T09:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Rex Saddle' LIMIT 1),     (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1, 10, 'completed', '2026-04-09T13:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Rare Flower' LIMIT 1),        (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    1, 15, 'completed', '2026-04-10T11:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Armor Set' LIMIT 1),      (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1, 10, 'completed', '2026-04-11T15:00:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Stegosaurus' LIMIT 1),        (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-04-12T10:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Industrial Forge' LIMIT 1),   (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1,  2, 'completed', '2026-04-13T14:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Noglin' LIMIT 1),             (SELECT id FROM customers WHERE email='chloe.d@gmail.com' LIMIT 1),    1,  8, 'completed', '2026-04-14T09:00:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Black Pearl' LIMIT 1),        (SELECT id FROM customers WHERE email='noah.p@outlook.com' LIMIT 1),   2, 30, 'completed', '2026-04-15T13:30:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Wyvern (Poison)' LIMIT 1),    (SELECT id FROM customers WHERE email='mia.k@gmail.com' LIMIT 1),      1,  8, 'completed', '2026-04-16T11:15:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Medical Brew' LIMIT 1),       (SELECT id FROM customers WHERE email='lucas.f@gmail.com' LIMIT 1),    2, 30, 'completed', '2026-04-17T15:45:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Tyranno Colossus' LIMIT 1),   (SELECT id FROM customers WHERE email='james.w@gmail.com' LIMIT 1),    1, 40, 'completed', '2026-04-18T10:45:00'),
((SELECT id FROM profiles WHERE email='123@pzr.com' LIMIT 1),   (SELECT id FROM products WHERE name='Tek Bow' LIMIT 1),            (SELECT id FROM customers WHERE email='sofia.m@outlook.com' LIMIT 1),  1,  9, 'completed', '2026-04-19T14:15:00'),
((SELECT id FROM profiles WHERE email='test@pzr.com' LIMIT 1),  (SELECT id FROM products WHERE name='Doedicurus' LIMIT 1),         (SELECT id FROM customers WHERE email='ethan.b@proton.me' LIMIT 1),    1,  8, 'completed', '2026-04-20T09:30:00');
